### ISSUE TITLE
can't open config ui

### ISSUE THREAD

**Issue by kekuwi** [btwonion/autodrop#11]
![image](https://github.com/btwonion/autodrop/assets/132612495/5ffe8f84-6eb8-4cc2-96b1-b26fcbe8d36c)
whenever i open the config using "o" my minecraft crash

**Comment by btwonion** [comment]
thank you for the report. i will take a look at it in the coming hours.

**Comment by Avtera** [comment]
i think the YACL dependencies is not forced (again)?

**Comment by btwonion** [comment]
Hi,
this is correct, I will change the dependency requirement in the next version.
