### ISSUE TITLE
Game crashes when you type a "," in the Item Filter

### ISSUE THREAD

**Issue by Hto0** [btwonion/autodrop#16]

**Comment by btwonion** [comment]
hi,
what game version are you playing on? Generally every item condition is only meant for one item. If you want to filter for multiple items you have to create multiple identifiers.

**Comment by Hto0** [comment]
I am very sorry, I do not know what happened but I gave a description but it's showing empty now. I used the latest version of Minecraft.

**Comment by btwonion** [comment]
I was able to recreate the error. Thanks for the report! For the time being, please just don't use commas (I mean they're not even accepted in Item Identifiers).

**Comment by btwonion** [comment]
this error is fixed with this commit: be8b4d4 and release 2.0.0-beta2
